### PR TITLE
Restore `visit_children` method. Fixes #82.

### LINKED ISSUE #82: Undefined method `visit_children' for an instance of FFI::Clang::Cursor (NoMethodError)
How to fix this error?
OS: macOS Sonoma 14.6.1
Apple clang version: 15.0.0 (clang-1500.3.9.4)
Ruby: 3.3.5
Gems:
ffi (1.17.0 arm64-darwin)
ffi-clang (0.10.0)

I try to run `bro-get.rb` from https://github.com/dkimitsa/robovm-bro-gen
But got this error:
```
/Users/roman/Downloads/bindings/robovm-bro-gen/bro-gen.rb:2911:in `process': undefined method `visit_children' for an instance of FFI::Clang::Cursor (NoMethodError)

            cursor.visit_children do |cursor, _parent|
                  ^^^^^^^^^^^^^^^
	from /Users/roman/Downloads/bindings/robovm-bro-gen/bro-gen.rb:3974:in `block in <main>'
	from /Users/roman/Downloads/bindings/robovm-bro-gen/bro-gen.rb:3816:in `each'
	from /Users/roman/Downloads/bindings/robovm-bro-gen/bro-gen.rb:3816:in `<main>'
```

### PR DESCRIPTION
**Pull request by ioquatix**
@cfis can I get your review on this?

### CODE REVIEW

File: spec/ffi/clang/cursor_spec.rb [hunk 1]
```diff
@@ -149,6 +149,16 @@
 		end
 		expect(counter).not_to equal(0)
 	end
+	
+	describe "#visit_children" do
+		it "allows us to visit its children" do
+			cursor.visit_children do |cursor, parent|
```
Comment (cfis) [inline spec/ffi/clang/cursor_spec.rb:155]: You need to add
counter = 0

Comment (ioquatix) [reply spec/ffi/clang/cursor_spec.rb:155]:
```suggestion
			counter = 0
			cursor.visit_children do |cursor, parent|
```

Comment (ioquatix) [reply spec/ffi/clang/cursor_spec.rb:156]: Thanks!
